workspace(name = "rules_clojure_example")

local_repository(
    name = "rules_clojure",
    path = "..",
)

load("@rules_clojure//clojure:maven.bzl", "clojure_maven_artifacts", "get_exclusions")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.3"
RULES_JVM_EXTERNAL_SHA = ""

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    # sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        "cider:cider-nrepl:0.25.5",
        "com.cemerick:pomegranate:1.1.0",
        "compliment:compliment:0.3.11",
        "me.raynes:fs:1.4.6"
    ] + clojure_maven_artifacts(maven),
    repositories = [
        "https://repo.clojars.org",
        "https://repo1.maven.org/maven2",
    ],
    # excluded_artifacts = get_exclusions()

        
)

register_toolchains("//:clojure_toolchain")
